#!/usr/bin/env bash
# Publish web-sized media to GitHub Releases, where the app's server fetches it.
#
#   release `photos`: ~4 MP JPEGs of every photo, same filename as the original
#   release `videos`: H.264/AAC transcodes of every video, <stem>.mp4 (the
#                     Pixel originals are HEVC, which most browsers can't play)
#
# Incremental: only files missing from the releases are generated and uploaded,
# so it is safe to re-run after adding photos or after an interruption.
#
# Where the originals come from (pick one):
#   SRC_DIR=Photos-3-001        local directory (default)
#   LFS_COMMIT=<sha>            the Git LFS copies stored in this repo's history
#                               (downloaded one batch at a time; counts against
#                               the repo owner's LFS bandwidth)
#
# Other env: GITHUB_REPO (default barafael/samothraki-june-2026),
#            OUT_DIR (default dist-media; kept for local serving),
#            BATCH (photos per upload batch, default 40).
# Needs: gh (authenticated, or GH_TOKEN), ffmpeg, cargo, curl.
set -euo pipefail
export LC_ALL=C # consistent sort order for comm

cd "$(dirname "$0")/.."

REPO="${GITHUB_REPO:-barafael/samothraki-june-2026}"
SRC_DIR="${SRC_DIR:-Photos-3-001}"
LFS_COMMIT="${LFS_COMMIT:-}"
OUT_DIR="${OUT_DIR:-dist-media}"
BATCH="${BATCH:-40}"

for tool in gh ffmpeg cargo curl; do
    command -v "$tool" >/dev/null || { echo "missing required tool: $tool" >&2; exit 1; }
done

mkdir -p "$OUT_DIR/photos" "$OUT_DIR/videos"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# ---------------------------------------------------------------- releases

ensure_release() { # tag title
    gh release view "$1" --repo "$REPO" >/dev/null 2>&1 && return
    echo "==> Creating release '$1'"
    gh release create "$1" --repo "$REPO" --title "$2" --latest=false \
        --notes "Web-sized media served by the app (generated by scripts/publish_media.sh). Not a software release."
}

uploaded_assets() { # tag -> asset names, one per line
    local id
    id="$(gh api "repos/$REPO/releases/tags/$1" --jq .id)"
    gh api --paginate "repos/$REPO/releases/$id/assets?per_page=100" \
        --jq '.[] | select(.state == "uploaded") | .name'
}

upload() { # tag file...
    local tag="$1"; shift
    [ "$#" -gt 0 ] || return 0
    echo "    uploading $# file(s) to '$tag'"
    gh release upload "$tag" --repo "$REPO" --clobber "$@"
}

# --------------------------------------------------------------- originals

list_originals() {
    if [ -n "$LFS_COMMIT" ]; then
        git cat-file -e "$LFS_COMMIT^{commit}" 2>/dev/null \
            || git fetch --quiet --depth=1 origin "$LFS_COMMIT"
        git ls-tree --name-only "$LFS_COMMIT" -- "$SRC_DIR/" | xargs -n1 basename
    else
        [ -d "$SRC_DIR" ] || { echo "no originals: $SRC_DIR does not exist (set SRC_DIR or LFS_COMMIT)" >&2; exit 1; }
        for f in "$SRC_DIR"/*; do if [ -f "$f" ]; then basename "$f"; fi; done
    fi
}

# Print the local path of original $1, downloading it first in LFS mode.
original() {
    if [ -z "$LFS_COMMIT" ]; then
        echo "$SRC_DIR/$1"
        return
    fi
    local dst="$WORK/originals/$1"
    mkdir -p "$WORK/originals"
    curl -fsSL --retry 3 -o "$dst" \
        "https://media.githubusercontent.com/media/$REPO/$LFS_COMMIT/$SRC_DIR/$1"
    echo "$dst"
}

# ------------------------------------------------------------------- main

ensure_release photos "Photos (web-sized)"
ensure_release videos "Videos (H.264)"

uploaded_assets photos | sort > "$WORK/have_photos"
uploaded_assets videos | sort > "$WORK/have_videos"
list_originals | sort > "$WORK/originals.txt"

grep -iE '\.(jpe?g)$' "$WORK/originals.txt" | comm -23 - "$WORK/have_photos" > "$WORK/todo_photos" || true
: > "$WORK/todo_videos"
while read -r name; do
    grep -qxF "${name%.*}.mp4" "$WORK/have_videos" || echo "$name" >> "$WORK/todo_videos"
done < <(grep -iE '\.(mp4|mov)$' "$WORK/originals.txt" || true)

echo "==> Photos: $(wc -l < "$WORK/todo_photos") to publish ($(wc -l < "$WORK/have_photos") already in release)"
echo "==> Videos: $(wc -l < "$WORK/todo_videos") to publish ($(wc -l < "$WORK/have_videos") already in release)"

cargo build --quiet --release -p photo-extract --bin gen-media
GEN_MEDIA="target/release/gen-media"

# Photos, in batches: fetch originals -> resize -> upload -> drop originals.
split -l "$BATCH" "$WORK/todo_photos" "$WORK/batch."
for batch in "$WORK"/batch.*; do
    [ -s "$batch" ] || continue
    srcs=(); outs=()
    while read -r name; do
        srcs+=("$(original "$name")")
        outs+=("$OUT_DIR/photos/$name")
    done < "$batch"
    "$GEN_MEDIA" --out "$OUT_DIR/photos" "${srcs[@]}"
    upload photos "${outs[@]}"
    rm -rf "$WORK/originals"
done

# Videos, one at a time (they're large).
while read -r name; do
    [ -n "$name" ] || continue
    out="$OUT_DIR/videos/${name%.*}.mp4"
    if [ ! -s "$out" ]; then
        src="$(original "$name")"
        echo "    transcoding $name"
        # Long edge <= 1920 (ffmpeg auto-rotates first, so portrait stays
        # portrait); first video + optional first audio stream only, which
        # drops the Pixel's motion-photo metadata streams; faststart for
        # streaming playback.
        ffmpeg -nostdin -y -loglevel error -i "$src" \
            -map "0:v:0" -map "0:a:0?" \
            -vf "scale='if(gt(iw,ih),min(1920,iw),-2)':'if(gt(iw,ih),-2,min(1920,ih))'" \
            -c:v libx264 -preset veryfast -crf 26 -pix_fmt yuv420p \
            -c:a aac -b:a 128k -movflags +faststart \
            "$out.part.mp4"
        mv "$out.part.mp4" "$out"
        rm -rf "$WORK/originals"
    fi
    upload videos "$out"
done < "$WORK/todo_videos"

echo "Done. https://github.com/$REPO/releases/tag/photos and .../tag/videos"
